/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface) {
    await queryInterface.bulkInsert(
      'Imgs',
      [
        {
          url: 'https://70.img.avito.st/image/1/1.OFMm0ra6lLoQZRa3WoJNGfRxkrCS8YI4n3GWvIZ3lg.64Ih0bmWbjaWTnTH5wYvGhDIiJtv7LWh2r2jksSztoo',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.wHsHG7a6bJIxrO6fC0S1MdW4apizOHoQvrhulKe-bg.0MZjMejDpeVsndukd5mhkeI1eUrSz6agKId9fnImjS0',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://70.img.avito.st/image/1/1.Bdykvba6qTWSCis4ouVwlnYerz8Qnr-3HR6rMwQYqw.FVMrIOPV2n5akMP3je--UeaC3ENoMhXtG5OJfYjAjrg',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://90.img.avito.st/image/1/1.nRF-Ora6MfhIjbP1SCCyQLOZN_LKGSd6x5kz_t6fMw._s7VOlGNaIVdokF5KD45S_QTOQyQsiUnVPMnAByVKJE',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://70.img.avito.st/image/1/1.Azf-m7a6r97ILC3T9Mt2fSw4qdRKuLlcRzit2F4-rQ.nla-PIi5M1SgEQQpgCBs1cRf1Y-NCYC7gJSr7lD3KoA',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.McrV0ra6nSPjZR8uu45EgAdxmylh8YuhbHGfJXV3nw.tSgk61HbndRhga6u0qtvLa4mJvxBzQF8Zl8MUjBP6uo',
          property_id: '1',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.8XN3cLa6XZpBx9-XGTuLT7vTW5DDU0sYztNfnNfVXw.SQnRJygBeHzuwcECa7BkBVrDE3dAVMv9u2ALLlAJwxI',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.XWermra68Y6dLXODndMnW2c594QfuecMEjnziAs_8w.ncTAkaN0LLEBneB0kCmQ1MaIhu0Ji5-G3_XNedEFgvQ',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://60.img.avito.st/image/1/1.7kyHILa6QqWxl8Co12uUcEuDRK8zA1QnPoNAoyeFQA.SpIqo2t-9aBBcO3rQgJ8GcKW6m5-vIhYoHmexE4wxzU',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.w59Qk7a6b3ZmJO17Wti5o5wwaXzksHn06TBtcPA2bQ.0gOfO-5PIlsFbDjNPsy9czxTj1v8VP-ijfxKxztX3Eo',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.-AJ6w7a6VOtMdNbmBoiCPrZgUuHO4EJpw2BW7dpmVg.kpx_SPmK41NJ0A0h4G57ecTIoPL_FtDQoblwg2KTUXY',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://80.img.avito.st/image/1/1.lfaPL7a6OR-5mLsSqWXvykOMPxU7DC-dNow7GS-KOw.9ta4P02wXz6YOcySAwVYBL6LWzMXDGbmOG0KLCNti5k',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.qSplO7a6BcNTjIfOO3HTFqmYA8nRGBNB3JgHxcWeBw.m2l57wHhHGhj3-laN-MQD214_wCPyiNqNmxjq15I5RY',
          property_id: '2',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://30.img.avito.st/image/1/1.jnmcOLa5IpCqj6CdjEb4ZIWaIJYimaCGqpQgki6NJpI.Cg-5Tv5IYX8LL5ADHTT269F6RnVRZfWMyTNNiXc2b4M',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://70.img.avito.st/image/1/1.E3jE57a5v5HyUD2c7qNlZd1FvZd6Rj2H8ku9k3ZSu5M.A6d-p5dY50XGgc1xyZ9V72mdCk0sibmL5ZWCKFM7Bps',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://30.img.avito.st/image/1/1.A5nyELa5r3DEpy19-FB1hOuyrXZMsS1mxLytckClq3I.bh0MhveMMv3qecKrW8nz9ArfEOsUCjOsbsfFoZAzmag',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.O5nzMLa5l3DFhxV9iVRNhOqSlXZNkRVmxZyVckGFk3I.eNtU4s1iotHknswVURDWgmykJoGV5e9drCPvXO9tJLM',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.g7jE5ra5L1HyUa1czpj1pd1ELVd6R61H8kotU3ZTK1M.oVgPF9AN_8CA2sENZZ_9W5ks2FvbJo3vBmvrqvQWeH4',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://90.img.avito.st/image/1/1.9fdqPba5WR5citsTDGaM6nOfWxjUnNsIXJFbHNiIXRw.0WXXY25qCB5oCIU4-mZ-5XbPjxlHE2TYJ75bC0rgzGk',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://10.img.avito.st/image/1/1.5nAlYLa5SpkT18iUZTufbTzCSJ-bwciPE8xIm5fVTps.mgpVkAAYnmUUW9WedwYgLoMKrbteX7WVRCi_QLWFGlQ',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://10.img.avito.st/image/1/1.clKKura53ru8DVy24usLT5MY3L00G1ytvBbcuTgP2rk.LnkQ0DcpThcuEd-AxACqUBfMgHj5TvH-TMt206-9H2c',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://30.img.avito.st/image/1/1.nnAknra5MpkSKbCUFLzobT08MJ-aP7CPEjIwm5YrNps.X4gVsKkQQZkS_XXka_vz7hmgPDNgu_3S2GfEzu8WaJ0',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://70.img.avito.st/image/1/1.rIX-Mba5AGzIhoJhqnfamOeTAmpAkIJ6yJ0CbkyEBG4.J-1Jw9u7o7K_su9q-fgWvGn6bg_Z9w-xg2O8-JrU_5o',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.7YdqM7a5QW5chMNjPFCamnORQ2jUksN4XJ9DbNiGRWw.akOyBv5kkCWkckJidP0cHUt6eAfm1q_RxDq7emqhU9E',
          property_id: '3',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://cdn.fishki.net/upload/post/201601/13/1810603/2_ja6.jpg',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://10.img.avito.st/image/1/1.qkZCLra5Bq90mYSiGli3T3OMBKn8j4S5dIIErfCbAq0._Wy-izwjCsaYjJ321jOLbTYkR5FfilZ8hgGrRbsDnjo',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.XjFp67a58thfXHDVWZ5DOFhJ8N7XSnDOX0fw2tte9to.q9LLc6rrvGZdGJRYStSi3Xa3fm1YVONj904NXbGfcAc',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://90.img.avito.st/image/1/1.owMN-La5D-o7T43nR7q-CjxaDeyzWY38O1QN6L9NC-g.MZ2FQZMbBwQSM4_h499wD0T8KmWlZFI1Ot4Qezu8inw',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.YDrAFLa5zNP2o07ejFV9M_G2ztV-tU7F9rjO0XKhyNE.Mp9o9HsANhPNBOHDuJsQyXqlyXbY2gjqxDXUF43d6hU',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.6p1VMra5RnRjhcR5DTnF2lKQRHLrk8RiY55EdueHQnY.ZjC6DvKPcPrSqYqKYQD63bDomTa0yqCqhwbP0NdG5yk',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://90.img.avito.st/image/1/1.8QbZBra5Xe_vsd_it33sD-ikX-lnp9_576pf7WuzWe0.mvkb_HOX8R_AfTIGSWcsEbZlgKYI00J0lbxhokxOLMI',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.Fb1gWba5uVRW7jtZRiUItFH7u1Le-DtCVvW7VtLsvVY.zT-f5iSM89Lw28N6wlR_xLiTVTlnMEGkHGtu0kwEPXU',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://60.img.avito.st/image/1/1.PFNSkra5kLpkJRK3JvYTFFUwkrzsMxKsZD6SuOAnlLg.4BI7Hnt6TLTXl8R9DXyDEhVwEWXOx8lt1c3MP10CakU',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.7FbBQba6QL_39sKylSrOLQDiRrV1YlY9eOJCuWHkQg.65Wk9ucgLKGzfKkTay1UjA7lSfP6LrfNdSACKjqqKm4',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.0Rfhjba6ff7XOv_zz-LzbCAue_RVrmt8WC5_-EEofw.FoD07HDQG_qRvHzrOfFIXv0gc-CFHoISWX23D-7wews',
          property_id: '4',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://40.img.avito.st/image/1/1.onicH7a6DpGqqIyc1AGMYEO8CJsoPBgTJbwMlzy6DA.mDmmuztToyzEWv6sJaq1x8Vz_-DI1E2o9f-FVLVOu80',
          property_id: '5',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.MnicH7a6npGqqByc9AMcYEO8mJsoPIgTJbyclzy6nA._b-5L_yfS5tvnaCyQAAZM8gKbmtH4POaWIrSWQwab0c',
          property_id: '5',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.tESSNba6GK2kgpqg9neaXE2WHqcmFg4vK5YaqzKQGg.kqNwRGtnkzlfxusd0V8j0IKFN82ZimxEuu0K0ux02eM',
          property_id: '5',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://30.img.avito.st/image/1/1.6l_wmba5RrbGLsS7qOKQPfI7RLBOOMSgxjVEtEIsQrQ.CNisQvzdGsraejeW2XSq-bDpH-6Uc3P6Huxy_chUxk4',
          property_id: '6',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.f1fFtba5077zAlGzt5hCa8gX0bh7FFGo8xnRvHcA17w.-x-fB1gcL3O6i7PXRr6O2prMf36IcdnRSUtO2Xrgl6Y',
          property_id: '6',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.w61uGba5b0RYru1JZBa11Hy7bULQuO1SWLVtRtysa0Y.zcPdjFw-1Kv8IBlQcSxQ7hIEcLFCLkta2kfPwe-lonM',
          property_id: '6',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.X5-IUba583a-5nF7umBDmoXz8XA28HFgvv3xdDrk93Q.FurnY9t1MrwZl9GdAObQNKsXVaHwr54uNnVgZKMkUFY',
          property_id: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://70.img.avito.st/image/1/1.RSJmWLa56ctQ72vGYGlZJ2v6683Y-WvdUPTrydTt7ck.-8yab1NwZlvXuge9wCRmMlcQu8YId8DwQ_RII7W914w',
          property_id: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://80.img.avito.st/image/1/1.4eQKPra5TQ08ic8ARA394QecTwu0n88bPJJPD7iLSQ8.LGNUYQkl4Y0ge4gTSZ1EJlWZVQBVBZeUqXD1f7B-gCM',
          property_id: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.4kpOsLa5TqN4B8yuBuP5T0MSTKXwEcy1eBxMofwFSqE.Q6S54NCK44EM9sk4gthtFAcW_P_nMgVat44eypULDA0',
          property_id: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.JbpmXLa5iVNQ6wteICA9v2v-i1XY_QtFUPCLUdTpjVE.YXhw64gjPMWMe6HLR1P3KHT0oHWY_EEDq-4wUd3EUvE',
          property_id: '7',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://60.img.avito.st/image/1/1.5BpAU7a5SPN25Mr-BHTueU3xSvX-8srldv9K8fLmTPE.Ke5N-md2n1wuvOMiE3BVRJpA4X3AQnqRyT04A28ZmFY',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.FlaK3ra5ur-8aTiyqv4cNYd8uLk0fzipvHK4vThrvr0.OsMtN7xV12nKqyzN8P6GDXpig2ovV16y3c1Otr6GEOc',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://20.img.avito.st/image/1/1.xmtan7a5aoJsKOiPWvimB1c9aITkPuiUbDNogOgqboA.mCGNMJkKCjB9lJlh2ycCiFJhxRayPksaUP4urN_yRHQ',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://10.img.avito.st/image/1/1.0iO4YLa5fsqO1_zHkAeyT7XCfMwGwfzcjsx8yArVesg.bbreHdHYUM-_GCdUXmzX1AIZA9fzU9gfAp1Gxa2pqTI',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://50.img.avito.st/image/1/1.2CSWmLa5dM2gL_bAqvO4SJs6dssoOfbboDR2zyQtcM8.REkMq589Ik76vt131H0Y9TIG7ZRXIB3BZBC41JR6cX8',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          url: 'https://00.img.avito.st/image/1/1.BQ-xMra5qeaHhSvrty5lY7yQq-APkyvwh56r5AOHreQ.04yQMJM3QJwWXsrbV_VEVSCEcICwS499OmJc2rGxAm8',
          property_id: '8',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('Imgs', null, {});
  },
};
